// Build js/data/league_logos.js: competition-id -> football-logos.cc PNG URL.
// Source: uploads/flcc_leagues/comp_logos.tsv ("FCM id \t Name \t asset path")
// Covers leagues (LEAGUES), domestic cups (CUPS) and UEFA club comps (UEFA) —
// the same single image source as the club badges (js/data/badges_remote.js).
import { readFileSync, writeFileSync } from 'fs';

const BASE = 'https://assets.football-logos.cc/logos/';
const rows = readFileSync(new URL('../uploads/flcc_leagues/comp_logos.tsv', import.meta.url), 'utf8')
  .split('\n')
  .map(l => l.trim())
  .filter(l => l && !l.startsWith('#'))
  .map(l => l.split('\t'));

const map = {};
const missing = [];
for (const [id, name, file] of rows) {
  if (!id || !file) { missing.push(id || name || '?'); continue; }
  map[id] = BASE + file;
}

const js = `// Generated by tools/build_league_logos.mjs — football-logos.cc logo URLs per competition id.
// League marks are 256px tiles; cup/UEFA marks use their 1500px asset (per-size hashes on the CDN).
// Covers LEAGUES, CUPS and UEFA ids from js/data/clubs.js. Same single image source as club badges.
// Regen: node tools/build_league_logos.mjs (source TSV: uploads/flcc_leagues/comp_logos.tsv)
export const COMP_LOGOS = ${JSON.stringify(map, null, 1)};
`;
writeFileSync(new URL('../js/data/league_logos.js', import.meta.url), js);
console.log(`league_logos.js written: ${Object.keys(map).length} competitions`);
if (missing.length) { console.warn('rows missing data:', missing); process.exitCode = 1; }
