// Build js/data/faces_local.js — manifest of headshots actually present in assets/faces/.
// playerFaceEl consults it so it never fires requests for local files that don't
// exist (which used to spam the console with hundreds of 404s).
// Regen after adding/removing face files: node tools/build_faces_manifest.mjs
import { readdirSync, writeFileSync } from 'fs';

const files = readdirSync('assets/faces').filter(f => /\.(png|jpe?g|webp)$/i.test(f));
const map = {};
for (const f of files) map[f.replace(/\.(png|jpe?g|webp)$/i, '')] = f;

writeFileSync('js/data/faces_local.js',
  `// Generated by tools/build_faces_manifest.mjs — local headshots in assets/faces/ (basename -> file).\n` +
  `export const FACES_LOCAL = ${JSON.stringify(map)};\n`);
console.log(`faces manifest: ${files.length} files -> js/data/faces_local.js`);
